# config/stocks_config.py
# Top 50 stocks (25 US + 25 India) with region and index mapping
# Extend this as you want. Index symbols chosen for common Yahoo tickers.

TOP_50_STOCKS = {
    # --- 25 US tickers ---
    "AAPL":       {"name":"Apple Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "MSFT":       {"name":"Microsoft Corp.","region":"US","index":"^GSPC","currency":"USD"},
    "AMZN":       {"name":"Amazon.com, Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "GOOGL":      {"name":"Alphabet Inc. (Class A)","region":"US","index":"^GSPC","currency":"USD"},
    "META":       {"name":"Meta Platforms, Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "NVDA":       {"name":"NVIDIA Corporation","region":"US","index":"^GSPC","currency":"USD"},
    "TSLA":       {"name":"Tesla, Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "JPM":        {"name":"JPMorgan Chase & Co.","region":"US","index":"^GSPC","currency":"USD"},
    "V":          {"name":"Visa Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "UNH":        {"name":"UnitedHealth Group","region":"US","index":"^GSPC","currency":"USD"},
    "MA":         {"name":"Mastercard Incorporated","region":"US","index":"^GSPC","currency":"USD"},
    "PG":         {"name":"Procter & Gamble","region":"US","index":"^GSPC","currency":"USD"},
    "HD":         {"name":"Home Depot, Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "BAC":        {"name":"Bank of America","region":"US","index":"^GSPC","currency":"USD"},
    "DIS":        {"name":"Walt Disney Co.","region":"US","index":"^GSPC","currency":"USD"},
    "PFE":        {"name":"Pfizer Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "MRK":        {"name":"Merck & Co.","region":"US","index":"^GSPC","currency":"USD"},
    "XOM":        {"name":"Exxon Mobil Corporation","region":"US","index":"^GSPC","currency":"USD"},
    "CVX":        {"name":"Chevron Corporation","region":"US","index":"^GSPC","currency":"USD"},
    "KO":         {"name":"Coca-Cola Co.","region":"US","index":"^GSPC","currency":"USD"},
    "NKE":        {"name":"Nike, Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "ORCL":       {"name":"Oracle Corporation","region":"US","index":"^GSPC","currency":"USD"},
    "INTC":       {"name":"Intel Corporation","region":"US","index":"^GSPC","currency":"USD"},
    "CSCO":       {"name":"Cisco Systems, Inc.","region":"US","index":"^GSPC","currency":"USD"},
    "ADBE":       {"name":"Adobe Inc.","region":"US","index":"^GSPC","currency":"USD"},

    # --- 25 India tickers (Yahoo India suffix .NS) ---
    "RELIANCE.NS":     {"name":"Reliance Industries Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "TCS.NS":          {"name":"Tata Consultancy Services","region":"IN","index":"^NSEI","currency":"INR"},
    "HDFCBANK.NS":     {"name":"HDFC Bank Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "INFY.NS":         {"name":"Infosys Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "ICICIBANK.NS":    {"name":"ICICI Bank Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "HINDUNILVR.NS":   {"name":"Hindustan Unilever Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "ITC.NS":          {"name":"ITC Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "KOTAKBANK.NS":    {"name":"Kotak Mahindra Bank Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "LT.NS":           {"name":"Larsen & Toubro Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "SBIN.NS":         {"name":"State Bank of India","region":"IN","index":"^NSEI","currency":"INR"},
    "AXISBANK.NS":     {"name":"Axis Bank Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "BHARTIARTL.NS":   {"name":"Bharti Airtel Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "BAJAJ-AUTO.NS":   {"name":"Bajaj Auto Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "ASIANPAINT.NS":   {"name":"Asian Paints Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "HCLTECH.NS":      {"name":"HCL Technologies Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "WIPRO.NS":        {"name":"Wipro Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "SUNPHARMA.NS":    {"name":"Sun Pharmaceutical Industries","region":"IN","index":"^NSEI","currency":"INR"},
    "MARUTI.NS":       {"name":"Maruti Suzuki India Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "TITAN.NS":        {"name":"Titan Company Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "ULTRACEMCO.NS":   {"name":"UltraTech Cement Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "ONGC.NS":         {"name":"Oil & Natural Gas Corporation Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "POWERGRID.NS":    {"name":"Power Grid Corporation of India","region":"IN","index":"^NSEI","currency":"INR"},
    "NTPC.NS":         {"name":"NTPC Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "BRITANNIA.NS":    {"name":"Britannia Industries Ltd","region":"IN","index":"^NSEI","currency":"INR"},
    "HDFC.NS":         {"name":"HDFC Ltd","region":"IN","index":"^NSEI","currency":"INR"},
}
